---
docker_net_addr: "172.19.0.0/16"
docker_net_prefix: "{{ docker_net_addr | ipaddr('prefix') }}"
docker_net_gateway: "{{ docker_net_addr | ipaddr(1) | ipaddr('address') }}"
docker_net_iprange: "{{ docker_net_addr | ansible.netcommon.ipsubnet(docker_net_prefix | int + 2, 0) }}"

compose_net_iprange: "{{ docker_net_addr | ansible.netcommon.ipsubnet(docker_net_prefix | int + 2, 1) }}"
compose_db_name: pdns
compose_db_user: pdns
compose_db_pass: secret
compose_pdns_secret: secret
compose_pdns_password: secret

pdns_namespace: pdns
pdns_db_user: pdns
pdns_db_pass: secret
pdns_db_name: pdns
pdns_api_key: pdns
pdns_api_secret: secret

metallb_namespace: metallb-system
metallb_net_iprange: "{{ docker_net_addr | ansible.netcommon.ipsubnet(docker_net_prefix | int + 1, -1) }}"

haproxy_namespace: haproxy-system
